apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Ebiz
  annotations:
    github.com/project-slug: wamanrajesh/Ebiz
     backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guests
